##
## Account Properties
##

    # Liferay Employee
    kb.email.address.1=lesa.qa.cse.1@liferay.com.broken
    # Customer
    kb.email.address.2=lesa.qa.customer@test.com.broken
    # Partner
    kb.email.address.3=lesa.qa.partner@test.com.broken
    # Trial User
    kb.email.address.4=kb.qa.trial@test.com.broken
    # Content Creator
    kb.email.address.5=kb.qa.content.creator@liferay.com.broken
    # KB Admin
    kb.email.address.6=lesa.qa.admin@liferay.com.broken

    kb.email.password.1=test
    kb.email.password.2=test
    kb.email.password.3=test
    kb.email.password.4=test
    kb.email.password.5=test
    kb.email.password.6=test

##
## Component Names
##

    component.names=support-qa

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Properties
##

    customer.liferay.url=https://customer-nightly.liferay.com

##
## Testray
##

    testray.project.name=Customer Support

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp