import de.undercouch.gradle.tasks.download.Download

import java.util.regex.Matcher

import org.gradle.internal.os.OperatingSystem
import org.gradle.util.GUtil

buildscript {
	repositories {
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}

		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}

	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.poshi.runner", version: "3.0.64"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.source.formatter", version: "5.1.119"
		classpath group: "de.undercouch", name: "gradle-download-task", version: "3.2.0"
		classpath group: "net.saliman", name: "gradle-properties-plugin", version: "1.4.6"
	}
}

apply plugin: "com.liferay.source.formatter"
apply plugin: "net.saliman.properties"

task cleanWebDriver(type: Delete)
task downloadInternetExplorerDriver(type: Download)
task unzipInternetExplorerDriver(type: Copy)

if (!hasProperty("operatingSystem")) {
	StringBuilder sb = new StringBuilder()

	OperatingSystem operatingSystem = OperatingSystem.current()

	if (operatingSystem.linux) {
		sb.append "linux"
	}
	else if (operatingSystem.macOsX) {
		sb.append "mac"
	}
	else if (operatingSystem.windows) {
		sb.append "windows"
	}
	else {
		throw new IllegalStateException("Unsupported operating system")
	}

	if (operatingSystem.toString().contains("64")) {
		sb.append "64"
	}
	else {
		sb.append "32"
	}

	ext.operatingSystem = sb.toString()
}

if (browser == "internet.explorer" && !operatingSystem.contains("win")) {
	throw new IllegalStateException("Internet Explorer is not supported on your operating system")
}

File webDriverRootDir = new File(buildDir, "webdriver")

allprojects {
	apply plugin: "net.saliman.properties"
}

cleanWebDriver {
	delete webDriverRootDir
}

downloadInternetExplorerDriver {
	String ieDriverServerOs

	if (operatingSystem == "win64") {
		ieDriverServerOs = "x64"
	}
	else {
		ieDriverServerOs = "Win32"
	}

	dest new File(webDriverRootDir, "iedriver/${internetExplorerDriverVersion}/${operatingSystem}/IEDriverServer_${ieDriverServerOs}_${internetExplorerDriverVersion}.zip")
	overwrite false
	src "http://selenium-release.storage.googleapis.com/${_parseMajorVersion(seleniumVersion)}/IEDriverServer_${ieDriverServerOs}_${internetExplorerDriverVersion}.zip"
}

unzipInternetExplorerDriver {
	dependsOn downloadInternetExplorerDriver
	from zipTree(downloadInternetExplorerDriver.dest)
	into new File(webDriverRootDir, "iedriver/${internetExplorerDriverVersion}/${operatingSystem}")
}

subprojects {
	apply plugin: "com.liferay.poshi.runner"
	apply plugin: "com.liferay.source.formatter"

	clean {
		delete "test.case.method.names.properties"
		delete "test.generated.properties"
		delete "test-results"
		delete "tests"

		dependsOn cleanWebDriver
	}

	configurations {
		sikuliComplete
	}

	dependencies {
		["x86", "x86_64"].each {
			sikuliComplete classifier: "linux-${it}", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
			sikuliComplete classifier: "windows-${it}", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
		}

		sikuliComplete classifier: "macosx-x86_64", group: "org.bytedeco.javacpp-presets", name: "opencv", version: poshiRunner.openCVVersion
	}

	poshiRunner {
		baseDir = "test/functional"
		openCVVersion = "2.4.10-0.10"

		poshiProperties.put "browser.type", browser.replaceAll("\\.", "")
		poshiProperties << _getTestProperties(project)

		browser = poshiProperties.get("browser.type")

		if (browser == "internet.explorer") {
			poshiProperties.put "selenium.executable.dir.name", "${unzipInternetExplorerDriver.destinationDir}${File.separator}"
			poshiProperties.put "selenium.ie.driver.executable", "IEDriverServer.exe"
		}

		List<File> propertiesFiles = new ArrayList<>()

		propertiesFiles.addAll(_getCustomPropertiesFiles("test", rootProject.projectDir))

		propertiesFiles.addAll(_getCustomPropertiesFiles("test", project.projectDir))

		poshiPropertiesFiles = propertiesFiles

		version = poshiRunnerVersion
	}

	repositories {
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}

	runPoshi {
		if (browser == "internet.explorer") {
			dependsOn unzipInternetExplorerDriver
		}
	}
}

repositories {
	maven {
		url "https://repository-cdn.liferay.com/nexus/content/groups/public"
	}
}

private static Properties _expandProperties(Properties properties) {
	boolean propertyExpanded = true

	while (propertyExpanded) {
		propertyExpanded = false

		Set<String> propertyNames = properties.stringPropertyNames()

		for (String propertyName : propertyNames) {
			String propertyValue = properties.getProperty(propertyName)

			Map<String, String> replacements = new HashMap<>()

			propertyValue.eachMatch("\\\$\\{.+?\\}") {
				group ->
				String name = group.replace("\${", "").replace("}", "")

				if (propertyNames.contains(name) && group != properties.getProperty(name)) {
					replacements.put(group, properties.getProperty(name))

					propertyExpanded = true
				}
			}

			for (String group : replacements.keySet()) {
				propertyValue = propertyValue.replace(group, replacements.get(group))
			}

			properties.setProperty(propertyName, propertyValue)
		}
	}

	properties
}

private static Properties _getCustomProperties(String prefix, File dir) {
	Properties properties = new Properties()

	for (File propertiesFile in _getCustomPropertiesFiles(prefix, dir)) {
		properties << GUtil.loadProperties(propertiesFile)
	}

	properties
}

private static List<File> _getCustomPropertiesFiles(String prefix, File dir) {
	List<String> propertiesFileNames = ["${prefix}.properties", "${prefix}-ext.properties"]

	if (System.env.HOSTNAME) {
		propertiesFileNames << "${prefix}.${System.env.HOSTNAME}.properties"
	}

	if (System.env.HOST) {
		propertiesFileNames << "${prefix}.${System.env.HOST}.properties"
	}

	if (System.env.COMPUTERNAME) {
		propertiesFileNames << "${prefix}.${System.env.COMPUTERNAME}.properties"
	}

	if (System.env.USER) {
		propertiesFileNames << "${prefix}.${System.env.USER}.properties"
	}

	List<File> propertiesFiles = new ArrayList<>()

	for (String propertiesFileName in propertiesFileNames) {
		File propertiesFile = new File(dir, propertiesFileName)

		if (propertiesFile.exists()) {
			propertiesFiles.add(propertiesFile)
		}
	}

	propertiesFiles
}

private Properties _getTestProperties(Project project) {
	Properties properties = new Properties()

	properties << _getCustomProperties("test", rootProject.projectDir)

	if (project != rootProject) {
		properties << _getCustomProperties("test", project.projectDir)
	}

	_expandProperties(properties)
}

private static String _parseMajorVersion(String version) {
	Matcher matcher = version =~ /^([0-9]+)\.([0-9]+).*/

	if (!matcher.matches()) {
		throw new IllegalArgumentException("${version} is not a valid version string")
	}

	"${matcher.group(1)}.${matcher.group(2)}"
}