##
## CI
##

    test.batch.property.query=testray.main.component.name == 'KLM'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'KLM')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'KLM')

##
## Poshi
##

    portal.url=http://192.168.118.9:8081/en/web/communicatie/home

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=FlightOperations,GroundServices

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.klm.portal.url.uat=http://192.168.118.9:8081/en/web/communicatie/home

    test.this.klm.test.account.uat.admin.login=test
    test.this.klm.test.account.uat.admin.password=test

    test.this.klm.test.account.webserver.user.login=test
    test.this.klm.test.account.webserver.user.password=test