##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Yusen'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Yusen')

    test.batch.property.query[uat]=\
        (test.env == "dev") AND \
        (testray.main.component.name == 'Yusen')

##
## Poshi
##

    portal.url=https://yvfebooking-dev.lxc.liferay.com

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=HomePage

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.yusen.portal.url.dev=https://yvfebooking-dev.lxc.liferay.com

    test.this.yusen.test.account.dev.admin.login=qa-leads@liferay.com