##
## Account Properties
##

    patcher.admin.email.address=test@liferay.com
    patcher.admin.password=liferay

    zendesk.admin.email.address=zendesk.admin@liferay.com.broken
    zendesk.admin.password=zendeskqauser

    zendesk.api.token=H5vC4cxSZdgZdKYVTDNPdmTKXqVUeQAmUWxVfIC4

##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=patcher-portal

##
## Test Batch
##

    test.batch.axis.count=13
    test.batch.property.query=testray.main.component.name == 'Support QA'

    test.batch.property.query[websites-patcher-portal-daily]=\
        (priority == "5" OR priority == "4")

    test.batch.property.query[websites-patcher-portal-weekly]=\
        (priority == "3" OR priority == "2")

##
## Test Case
##

    test.case.available.property.names=\
        ignore,\
        priority,\
        test.group,\
        testray.main.component.name

##
## Test Properties
##

    build.compile.completion.poll.interval.in.minutes=10
    build.merge.completion.poll.interval.in.seconds=90
    build.rebase.completion.poll.interval.in.seconds=90
    build.completion.poll.maximum.iterations=30

    builder.url=http://cloud-10-50-0-133

    fix.completion.poll.interval.in.seconds=90
    fix.completion.poll.maximum.iterations=30

    portal.url=http://cloud-10-50-0-130

    zendesk.liferay.url=https://liferaysupport1528999723.zendesk.com

##
## Testray
##

    testray.project.name=Patcher

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp