##
## Poshi
##

    portal.url=http://senac.local:8080/web/guest

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        test.env,\
        testray.main.component.name

    test.name=ESBookDetails,ESHomePage,ESSearch,ESShoppingCart,SSPCourse,SSPHomePage,SSPOffers,SSPSearchBar

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.editora.senac.portal.url=http://senac.local:8080/web/editora-senac
    test.this.editora.senac.portal.login.url=http://senac.local:8080/web/editora-senac/login
    test.this.senac.test.account.uat.admin.login=liferay@sp.senac.br
    test.this.senac.test.account.uat.admin.password=test