##
## Account Properties
##

    partner.admin.email.address=testqa@liferay.com
    partner.admin.password=t3stq@prm.com

##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=partner

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
		test.group,\
		testray.main.component.name,\
		type

##
## Test Properties
##

	partner.portal.url=https://partner-uat.lxc.liferay.com/web/partner-portal
	partner.portal.url.login=https://partner-uat.lxc.liferay.com/login

##
## Testray
##

    testray.project.name=Partner

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp