##
## Poshi
##

    output.dir.name=downloads

    portal.url=http://publicwebsite--uat-lxc-liferay-com.i3v2-modl.lxc.liferay.com:8080/en/web/atlantia

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=ATLAboutUs,ATLHomePage,ATLPressRelease,ATLSearch,ATLTranslate,IJAdmin,IJContentPage,IJHomePage

##
## Test This
##

    test.this.atlantia.portal.url=http://publicwebsite--uat-lxc-liferay-com.i3v2-modl.lxc.liferay.com:8080/en/web/atlantia
    test.this.atlantia.portal.partial.url=http://publicwebsite--uat-lxc-liferay-com.i3v2-modl.lxc.liferay.com:8080
    test.this.infrajournal.portal.url=http://publicwebsite--uat-lxc-liferay-com.i3v2-modl.lxc.liferay.com:8080/en/web/infrajournal
    test.this.atlantia.portal.login.admin.url=http://publicwebsite--uat-lxc-liferay-com.i3v2-modl.lxc.liferay.com:8080/en/web/guest/s6tu9mejqjmr2u2u
    test.this.atlantia.portal.admin.login=fabio.lanza@atlantia.com
    test.this.atlantia.portal.admin.password=password