##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Project Name'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Project Name')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Project Name')

##
## Poshi
##

    portal.url=http://<project-modl-url>

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.projectname.portal.url.modl=http://<project-modl-url>
    test.this.projectname.portal.url.prod=http://<project-prod-url>

    test.this.projectname.test.account.modl.admin.login=<modl-admin-login>

    test.this.projectname.test.account.modl.user.login=<modl-user-login>