##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Goodwill'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Goodwill')

    test.batch.property.query[modl]=\
        (test.env == "modl") AND \
        (testray.main.component.name == 'Goodwill')

##
## Poshi
##

    portal.url=http://goodwill--uat-lxc-liferay-com-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.goodwill.portal.url.modl=http://goodwill--uat-lxc-liferay-com-modl.lxc.liferay.com:8080

    test.this.goodwill.test.account.modl.admin.login=liferaydevsecops@liferay.com