environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=exchange.goodwill.org - $(start.time)
testrayCasePriority=1
testrayComponentName=Goodwill
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Nightly
testrayServerURL=https://testray.liferay.com
testrayTeamName=Goodwill