##
## Account Properties
##

    okta.liferay.login.dev.url=https://login-dev.liferay.com
    okta.user.email.address=amos.fong@liferay.com.broken

##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Customer Portal 2.0'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Customer Portal 2.0')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Customer Portal 2.0')

##
## Poshi
##

    portal.url=http://support--uat-lxc-liferay-com-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=CP2ActivationKeysForCommerce,CP2DeactivateKey,CP2DeveloperKeys,CP2DXPCloudSetup,CP2EnterpriseSearch,CP2ExportingActivationKeys,CP2KeysManagement,CP2MultipleIndividualKeys,CP2NewKeyGenerationPart2B,CP2ProjectBreadcrumb,CP2QuickLinks,CP2SetupAC,CP2SLACard,CP2SubscriptionTerms,CP2TeamMembers,CP2TeamMembersRoleLimit,CustomerPortalSite

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.cp.portal.url.modl=http://support--uat-lxc-liferay-com-modl.lxc.liferay.com:8080
    test.this.cp.portal.url.prod=https://support.liferay.com