##
## Component Names
##

    component.names=salesforce

##
## Salesforce Account Properties
##

    salesforce.email.address.qa=is-sales-qa@liferay.com.qa
    salesforce.email.password.qa=l1f3ray151
    salesforce.email.address.sales=is-sales-qa@liferay.com.sales
    salesforce.email.password.sales=l1f3ray151
    salesforce.email.address.sales3=is-sales-qa@liferay.com.sales3
    salesforce.email.password.sales3=l1f3ray151

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == "salesforce" AND inactive == null

##
## Test Case
##

    test.case.available.property.names=testray.main.component.name,inactive

##
## Testray
##

    testray.project.name=Salesforce

##
## Utilities
##

    portal.sales.url=https://test.salesforce.com/

    test.dirs=testFunctional
    test.support.dirs=\
        ../partner/testFunctional,\
        ../shared