##
## CI
##

    browser.chrome.bin.args=\
        disable-dev-shm-usage \
        disable-gpu \
        password-store=basic

    component.names=liferay-cloud-platform

    test.batch.property.query=true

    test.batch.property.query[smoke]=\
        (testray.main.component.name == 'Liferay Cloud Platform')

    test.batch.group.ignore.regex=testray.main.component.name

##
## Poshi
##

    test.case.available.property.names=\
        testray.main.component.name

    test.dirs=testFunctional/

##
## Test This
##

    test.this.account.user1.email=qaposhiuser1@test.com
    test.this.account.user1.password=vGfOY&s6z@A1Zkr
    test.this.account.user2.email=qaposhiuser2@test.com
    test.this.account.user2.password=Paj-GH*utG1WQ8
    test.this.account.user3.email=qaposhiuser3@test.com
    test.this.account.user3.password=NAJ+C0Ezu&kXTb6
    test.this.account.user4.email=qaposhiuser4@test.com
    test.this.account.user4.password=nMo,10c!jrgmiiH
    test.this.lcp.test.guest.user.email=poshi.guest@liferay.cloud
    test.this.lcp.test.guest.user.password=KF@BL1F36nsi.Tz
    test.this.lcp.test.team.user.email=poshi.tester@liferay.cloud
    test.this.lcp.test.team.user.password=nGs6!R@YoL1PXm5
    test.this.lcp.test.base.url.api=api.liferay.coffee

##
## Testray
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=Liferay Cloud Platform
    testray.routine.name=Development Daily

    testray.team.names=\
        cloud

    testray.team.cloud.component.names=\
        liferay-cloud-platform