##
## Account Properties
##
    learn.admin.email.address=is-qa@liferay.com
    learn.admin.password=NAH@uth_xjr-chv2vhg

##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=learn

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Testray
##

    testray.project.name=Learn

##
## Test Properties
##


    portal.url=http://learn-uat.liferay.com
	www.learn.url=http://learn-uat.liferay.com

##
## Utilities
##
	test.base.dir.name=testFunctional
	test.include.dir.names=../shared
	output.dir.name=../tmp