##
## Component Names
##

    component.names=support-qa

##
## LESA Account Properties
##

    lesa.cse.name.1=QATest CSE1
    lesa.manager.name.2=QATest Manager
    lesa.cas.name.3=QATest CAS
    lesa.customer.name.4=QATest Customer
    lesa.customer.name.5=
    lesa.partner.name.6=QATest Partner
    lesa.admin.name.7=QATest Admin
    lesa.cwatcher.name.8=QATest CWatcher
    lesa.pwatcher.name.9=QATest PWatcher
    lesa.cse.name.10=QATest CSE2

    lesa.email.address.1=lesa.qa.cse.1@liferay.com.broken
    lesa.email.address.2=lesa.qa.manager@liferay.com.broken
    lesa.email.address.3=lesa.qa.cas@liferay.com.broken
    lesa.email.address.4=lesa.qa.customer@test.com.broken
    lesa.email.address.5=
    lesa.email.address.6=lesa.qa.partner@test.com.broken
    lesa.email.address.7=lesa.qa.admin@liferay.com.broken
    lesa.email.address.8=lesa.qa.customerwatcher@test.com.broken
    lesa.email.address.9=lesa.qa.partnerwatcher@test.com.broken
    lesa.email.address.10=lesa.qa.cse.2@liferay.com.broken

    lesa.email.password.1=lesaqauser
    lesa.email.password.2=lesaqauser
    lesa.email.password.3=lesaqauser
    lesa.email.password.4=lesaqauser
    lesa.email.password.5=lesaqauser
    lesa.email.password.6=lesaqauser
    lesa.email.password.7=lesaqauser
    lesa.email.password.8=lesaqauser
    lesa.email.password.9=lesaqauser
    lesa.email.password.10=lesaqauser

##
## Marketplace Account Properties
##

    marketplace.email.address.1=liferay.qa.marketplace@gmail.com.broken
    marketplace.email.address.2=liferay.qa.marketplace.1@gmail.com.broken
    marketplace.email.address.3=lrqa.merchant.1@liferay.com
    marketplace.email.address.4=lrqa.personal.2@liferay.com
    marketplace.email.address.5=liferay.qa.admin@liferay.com
    marketplace.email.address.6=liferay.qa.marketplace.2@gmail.com.broken

    marketplace.email.password.1=test
    marketplace.email.password.2=test
    marketplace.email.password.3=Liferay123
    marketplace.email.password.4=Liferay123
    marketplace.email.password.5=liferayqa
    marketplace.email.password.6=test

##
## Test Batch
##

    test.batch.group.ignore.regex=lesa\.acceptance|priority
    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=lesa.acceptance,testray.main.component.name

##
## Testray
##

    testray.project.name=LESA

##
## Utilities
##

    portal.url=https://www-support-2.liferay.com

    test.dirs=testFunctional

    test.support.dirs=\
        ../lesa/testFunctional,\
        ../marketplace/testFunctional,\
        ../shared