##
## CI
##

    test.batch.property.query=testray.main.component.name == 'PPL'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'PPL')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'PPL')

##
## Poshi
##

    portal.url=https://ppl:X3ilA391dk1d@ppl-portal-preview.lnd.bz/en

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.ppl.portal.url.uat=https://ppl:X3ilA391dk1d@ppl-portal-preview.lnd.bz/en
    test.this.ppl.portal.url.prod=http://ppl.cz

    test.this.ppl.test.account.uat.admin.login=<uat-admin-login>
    test.this.ppl.test.account.uat.admin.password=<uat-admin-password>

    test.this.ppl.test.account.uat.user.login=<uat-user-login>
    test.this.ppl.test.account.uat.user.password=<uat-user-password>

    test.this.ppl.test.account.webserver.user.login=ppl
    test.this.ppl.test.account.webserver.user.password=X3ilA391dk1d