environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=ppl.cz - $(start.time)
testrayCasePriority=1
testrayComponentName=PPL
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Daily
testrayServerURL=https://testray.liferay.com
testrayTeamName=PPL