##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Marina del Sol'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Marina del Sol')

    test.batch.property.query[uat]=\
        (test.env == "modl") AND \
        (testray.main.component.name == 'Marina del Sol')

##
## Poshi
##

    portal.url=http://mds--uat-lxc-liferay-com-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=MDSCasinos,MDSHotels

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.marinadelsol.portal.url.modl=http://mds--uat-lxc-liferay-com-modl.lxc.liferay.com:8080