environmentBrowserName=Google Chrome 100
environmentOperatingSystemName=Ubuntu 22.04.1
projectDir=.
testrayBuildName=marinadelsol.cl - $(start.time)
testrayCasePriority=1
testrayComponentName=Marina del Sol
testrayProductVersion=1.x
testrayProjectName=LXC
testrayRoutineName=MODL Daily
testrayServerURL=https://testray.liferay.com
testrayTeamName=Marina del Sol