##
## Account Properties
##

    www.admin.email.address=is-qa@liferay.com
    www.admin.password=NAH@uth_xjr-chv2vhg

##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=www

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Test Properties
##

    portal.url=https://www-uat.liferay.com
    www.liferay.url=https://www-uat.liferay.com

##
## Testray
##

    testray.project.name=WWW

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp