##
## CI
##

    test.batch.property.query=testray.main.component.name == 'MARKWINS'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'MARKWINS')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'MARKWINS')

##
## Poshi
##

    portal.url=http://localhost:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.markwins.portal.url.uat=http://localhost:8080
    test.this.markwins.portal.url.prod=http://localhost:8080

    test.this.markwins.test.account.uat.admin.login=lifeadm
    test.this.markwins.test.account.uat.admin.password=test