##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=marketplace

##
## Known Broken Links
##

    known.broken.links=\
        http://liferay7.smc.it/web/tales,\
        https://git.mimacom.com/projects/CTA/repos/angular-liferay-portlet-seed/browse/src,\
        https://nexus.mimacom.com/content/repositories/mimacom-releases-open/org/mimacom/liferay/plugins/hooks/landing_page_manager-hook/1.0.7.0/landing_page_manager-hook-1.0.7.0-sources.jar,\
        https://nexus.mimacom.com/content/repositories/mimacom-releases-open/org/mimacom/liferay/plugins/portlets/ctx-migration-portlet/1.0.10.0/ctx-migration-portlet-1.0.10.0-sources.jar,\
        https://projects.savoirfairelinux.com/projects/ctr-liferay/wiki/Hook_for_French_translations,\
        https://projects.savoirfairelinux.com/projects/ctr-liferay/wiki/Portlet_-_ETL_examples

##
## Marketplace Account Properties
##

    marketplace.admin.email.address=is-qa@liferay.com
    marketplace.admin.password=NAH@uth_xjr-chv2vhg

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Test Properties
##

    portal.url=https://www-uat.liferay.com
    www.liferay.url=https://www-uat.liferay.com

##
## Testray
##

    testray.project.name=Marketplace

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp