##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=marketplace

##
## Known Broken Links
##

    known.broken.links =\
		https://nexus.mimacom.com/content/repositories/mimacom-releases-open/org/mimacom/liferay/plugins/portlets/ctx-migration-portlet/1.0.10.0/ctx-migration-portlet-1.0.10.0-sources.jar,\
		https://nexus.mimacom.com/content/repositories/mimacom-releases-open/org/mimacom/liferay/plugins/hooks/landing_page_manager-hook/1.0.7.0/landing_page_manager-hook-1.0.7.0-sources.jar,\
		http://liferay7.smc.it/web/tales,\
		https://git.mimacom.com/projects/CTA/repos/angular-liferay-portlet-seed/browse/src,\
		https://projects.savoirfairelinux.com/projects/ctr-liferay/wiki/Portlet_-_ETL_examples,\
		https://projects.savoirfairelinux.com/projects/ctr-liferay/wiki/Hook_for_French_translations

##
## Marketplace Account Properties
##

    marketplace.admin.email.address=is-qa@liferay.com
    marketplace.admin.password=NAH@uth_xjr-chv2vhg

##
## Testray
##

    testray.project.name=Marketplace

##
## Test Batch
##

    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=\
        test.group,\
        testray.main.component.name,\
        type

##
## Utilities
##

    test.base.dir.name=testFunctional
	test.include.dir.names=../shared
	output.dir.name=../tmp

##
## Test Properties
##

    portal.url=https://www-uat.liferay.com
	www.liferay.url=https://www-uat.liferay.com