##
## Account Properties
##

    ac.email=acqa@liferay.com
    ac.password=b3nnybr0ws3r
    ac.url=https://analytics-uat.liferay.com

    portal.account.persona1.email=benny.browser@liferay.com
    portal.account.persona1.password=r3m3mb3r
    portal.url=https://www.liferay.com

##
## Poshi Properties
##

    test.case.available.property.names=\
        testray.main.component.name

    test.dirs=testFunctional/

##
## CI
##

    browser.chrome.bin.args=\
        disable-dev-shm-usage \
        disable-gpu \
        password-store=basic

    test.batch.property.query[analytics-cloud-generators]=\
        testray.main.component.name == "Generators"

    test.batch.property.query[analytics-cloud-verifiers]=\
        testray.main.component.name == "Verifiers"

    test.batch.group.ignore.regex=testray.main.component.name

##
## Testray Routines
##

    testray.build.name=ci:test:$(ci.test.suite) - $(jenkins.build.number) - $(jenkins.build.start)
    testray.project.name=Analytics Cloud
    testray.routine.name[analytics-cloud-generators]=Analytics Cloud Generators
    testray.routine.name[analytics-cloud-verifiers]=Analytics Cloud Verifiers