##
## Account Properties
##

    portal.email.address=benny.browser@liferay.com
    portal.admin.password=r3m3mb3r

    ac.email.address=acqa@liferay.com
    ac.admin.password=b3nnybr0ws3r

##
## CI
##

    test.batch.property.query[analytics-cloud-generators]=\
        testray.main.component.name == "Generators"
    
    test.batch.property.query[analytics-cloud-verifiers]=\
        testray.main.component.name == "Verifiers"

##
## Testray Routines
##

    testray.project.name=Analytics Cloud
    testray.routine.name[analytics-cloud-generators]=Analytics Cloud Generators
    testray.routine.name[analytics-cloud-verifiers]=Analytics Cloud Verifiers

##
## Poshi Properties
##

    test.case.available.property.names=\
        testray.main.component.name

    portal.url=https://analyticsqa.lxc.liferay.com
	ac.url=https://analytics-uat.liferay.com