##
## CI
##

    test.batch.property.query=testray.main.component.name == 'CROSIG'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'CROSIG')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'CROSIG')

##
## Poshi
##

    portal.url=http://localhost:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=Policy

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.crosig.portal.url.uat=http://localhost:8080
    test.this.crosig.portal.url.prod=http://localhost:8080

    test.this.crosig.test.account.uat.admin.login=scott.agent@mailinator.com
    test.this.crosig.test.account.uat.admin.password=obj123

    test.this.crosig.test.account.uat.user.login=scott.agent@mailinator.com
    test.this.crosig.test.account.uat.user.password=obj123