##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Concluder'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Concluder')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Concluder')

##
## Poshi
##

    portal.url=http://dealmanagementplatform--uat-lxc-liferay-com.a2x9-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=HomePage,Objects

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.concluder.portal.url.modl=http://dealmanagementplatform--uat-lxc-liferay-com.a2x9-modl.lxc.liferay.com:8080
    test.this.concluder.portal.url.prod=https://dealmanagementplatform.lxc.liferay.com/

    test.this.concluder.test.account.modl.admin.login=test-concluder@lxc.app