##
## Admin Credentials
##

    admin.email.address=david.bhasme@liferay.com.broken
    admin.password=test

##
## Component Names
##

    component.names=liferay-sync

##
## Portal Instance
##

    test.portal.instance=true

##
## Test Batch
##

    test.batch.property.query=true

##
## Testray
##

    testray.project.name=Liferay Sync

##
## Utilities
##

    portal.url=https://sync-nightly.liferay.com

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp