##
## Account Properties
##

    mirror.user=er-hu@liferay.com
    mirror.password=n3tr1sk

##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=patcher-builder

##
## Test Batch
##

    test.batch.axis.count=5
    test.batch.property.query=true

    test.batch.property.query[websites-patcher-builder-daily]=\
        (priority == "5" OR priority == "4")

    test.batch.property.query[websites-patcher-builder-weekly]=\
        (priority == "3" OR priority == "2")

##
## Test Case
##

    test.case.available.property.names=\
        ignore,\
        priority,\
        test.group,\
        testray.main.component.name

##
## Test Properties
##

    job.completion.poll.interval.in.minutes=6
    job.completion.poll.maximum.iterations=30

    portal.url=http://cloud-10-50-0-133.liferay.com/

##
## Testray
##

    testray.project.name=Patcher

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp