##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Liferay Dev'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Liferay Dev')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Liferay Dev')

##
## Poshi
##

    portal.url=http://liferay-dev-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        test.env,\
        test.type,\
        testray.main.component.name

    test.name=LDAsk,LDBlogs,LDChat,LDGeneral,LDHomePage,LDProductionSmoke,LDProjects,LDSeo,LDSocialMedia

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.liferaydev.portal.url.uat=http://liferay-dev-modl.lxc.liferay.com:8080
    test.this.liferaydev.portal.url.prod=http://liferay.dev

    test.this.liferaydev.test.account.uat.admin.login=liferaydev-admin-uat@liferay.com

    test.this.liferaydev.test.account.uat.user.login=liferaydev-user-uat@liferay.com

    test.this.liferaydev.upgrade.log.dir=logs