##
## Account Properties
##

    customer.admin.email.address=amos.fong@liferay.com.broken
    customer.admin.password=wqd@NUX2jwv@bhp@gnz1

    dxp.cloud.api.token=4bccb189-f5a2-4063-82e5-3f11c7e4f6b2
    dxp.cloud.page.id=n9qmq1q6bk9y

    koroneiki.api.token=Woth6ojfvvUvNwHu4MJiTrGq8vDatcu8HCG8SBAmiJn7nvcvxFf4R16No3VLCWzv
    koroneiki.non.permission.api.token=B70PxYFN4gktgNVDIBprdA6Gb5rtgR4HiYlh2IdQ3mSK1uAhdurNcfqtzclHreon
    koroneiki.non.permission.role.name=service_producer.4117919

    koroneiki.admin.email.address=test@liferay.com
    koroneiki.admin.password=R7.QR9g7pUvfmrcKKP6f

    okta.user.password=R7.QR9g7pUvfmrcKKP6f

    provisioning.admin.email.address=test@liferay.com
    provisioning.admin.password=y*fYsNufytjzDv8Y2pbR

    rabbitmq.admin.password=2sbvnkLnqyNBfK2R
    rabbitmq.admin.user.name=ken.duenwald

    support.admin.email.address=amos.fong@liferay.com.broken
    support.admin.password=test

    zendesk.admin.email.address=zendesk.admin@liferay.com.broken
    zendesk.admin.password=zendeskqauser

    zendesk.api.token=H5vC4cxSZdgZdKYVTDNPdmTKXqVUeQAmUWxVfIC4

    support.user.test.password=osbadminqauser

    provisioning.qa.user.password=provisioningqauser

    test.account.code=THESPACEPRO

##
## Browser
##

    browser.type=chrome

##
## Component Names
##

    component.names=support-qa

##
## Test Batch
##

    test.batch.group.ignore.regex=help\.center\.acceptance|help\.center\.smoke|priority
    test.batch.property.query=testray.main.component.name == 'Support QA'

##
## Test Case
##

    test.case.available.property.names=help.center.acceptance,help.center.smoke,type,testray.main.component.name

##
## Test Properties
##

    customer.portal.url=https://support-uat.liferay.com/home

    dxp.cloud.api.url=https://api.statuspage.io

    issues.zendesk.liferay.url=https://issues-zen.liferay.com/

    koroneiki.liferay.url=https://webserver-lrkoroneiki-uat.lfr.cloud
    koroneiki.liferay.web.id=liferay.com

    okta.api.token=00yD_AX5LXQ-5sPhelHTBNnwJGeGnYsMtqxf0vgX2U
    okta.liferay.login.dev.url=https://login-dev.liferay.com

    osb.admin.popup.title=OSB Admin - Control Panel

    osb.to.zendesk.sync.poll.interval.in.seconds=5
    osb.to.zendesk.sync.poll.maximum.iterations=35

    portal.url=https://webserver-lrkoroneiki-uat.lfr.cloud

    provisioning.liferay.url=https://webserver-lrprovisioning-uat.lfr.cloud
    provisioning.liferay.web.id=liferay.com

    rabbitmq.url=http://cloud-10-50-0-217:15672

    support.liferay.url=https://customer-uat.liferay.com
    support.liferay.web.id=liferay.com

    zendesk.liferay.url=https://liferaysupport1528999723.zendesk.com

##
## Testray
##

    testray.project.name=Help Center

##
## Utilities
##

    test.dirs=testFunctional
    test.support.dirs=../shared
    output.dir.name=../tmp