##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Alongsiders'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Alongsiders')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Alongsiders')

##
## Poshi
##

    portal.url=http://alongsiders--z4f3--uat-lxc-liferay-com-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=HomePage,Dashboards,Movements,ObjectsAdmin

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.alongsiders.portal.url.modl=http://alongsiders--z4f3--uat-lxc-liferay-com-modl.lxc.liferay.com:8080

    test.this.alongsiders.test.account.modl.admin.login=qa-leads@liferay.com