buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.poshi.defaults"

dependencies {
	poshiRunnerResources group: "com.liferay", name: "com.liferay.poshi.runner.resources", version: "1.0.15"
	poshiRunnerResources group: "com.liferay.poshi.runner.resources", name: "portal-master", version: "20230405-b774dca"
}

poshiRunner {
	version = "1.0.405"
}