##
## CI
##

    test.batch.property.query=testray.main.component.name == 'Cosette'

    test.batch.property.query[production]=\
        (test.env == "production") AND \
        (testray.main.component.name == 'Cosette')

    test.batch.property.query[uat]=\
        (test.env == "uat") AND \
        (testray.main.component.name == 'Cosette')

##
## Poshi
##

    output.dir.name=downloads

    portal.url=http://azor-com-modl.lxc.liferay.com:8080

    save.screenshot=false

    test.base.dir.name=testFunctional/

    test.case.available.property.names=\
        testray.main.component.name

    test.name=API,HomePageElements,HomePageNavigation

    test.support.dirs=../shared-poshi-code

##
## Test This
##

    test.this.cosette.azor.portal.url.uat=http://azor-com-modl.lxc.liferay.com:8080
    test.this.cosette.benicar.portal.url.uat=http://benicar-com-modl.lxc.liferay.com:8080
    test.this.cosette.tribenzor.portal.url.uat=http://tribenzor-com-modl.lxc.liferay.com:8080
    test.this.cosette.welchol.portal.url.uat=http://welchol-com-modl.lxc.liferay.com:8080
    test.this.cosette.welcholhcp.portal.url.uat=http://welcholhcp-com-modl.lxc.liferay.com:8080